<a href="https://colab.research.google.com/github/hominhlongg/Laptrinhpythonnangcao/blob/main/LAB02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
kingdoms=['Bacteria', 'Protozoa', 'Chromista', 
'Plantae', 'Fungi',
'Animalia']
print('Bai 1')
print('a:',kingdoms[0])
print('b:',kingdoms[5])
print('c:',kingdoms[:3])
print('d:',kingdoms[2:5])
print('e:',kingdoms[4:])
print('f:',kingdoms[1:0])
print('---------------------------')
print('Bai 2 : Using negative indices')
print('a:',kingdoms[-6])
print('b:',kingdoms[-1])
print('c:',kingdoms[-6:-3])
print('d:',kingdoms[-4:-1])
print('e:',kingdoms[-2:])
print('f:',kingdoms[-1:-2])
print('---------------------------')
print('Bai 3:')
appointments=['9:00', '10:30', '14:00', '15:00', 
'15:30']
list2=[]
list2.extend(appointments)
list2.append('16:30')
list2+=['16:30']
print('List default:',appointments)
print('New list:',list2)

Bai 1
a: Bacteria
b: Animalia
c: ['Bacteria', 'Protozoa', 'Chromista']
d: ['Chromista', 'Plantae', 'Fungi']
e: ['Fungi', 'Animalia']
f: []
---------------------------
Bai 2 : Using negative indices
a: Bacteria
b: Animalia
c: ['Bacteria', 'Protozoa', 'Chromista']
d: ['Chromista', 'Plantae', 'Fungi']
e: ['Fungi', 'Animalia']
f: []
---------------------------
Bai 3:
List default: ['9:00', '10:30', '14:00', '15:00', '15:30']
New list: ['9:00', '10:30', '14:00', '15:00', '15:30', '16:30', '16:30']

In [2]:
print('Bai 4')
numberlist=[4353, 2314, 2956, 3382, 9362, 3900]
numberlist.pop(3)
index=numberlist.index(9362)
numberlist.insert(4,4492)
numberlist.extend([5566,1830])
numberlist.reverse()
numberlist.sort()
print('List:',numberlist)
print('Index of 9362 in default list is:',index)
print('---------------------------')
print('Bai 5')
ha1=[]
alkaline_earth_metals=['beryllium',4,
                       'magnesium',12,
                       'calcium',20,
                       'strontium',38,
                       'barium',56,
                       'radium',88,]
index=alkaline_earth_metals.index('radium')
print('Index of radium is: ',index)
print('Positive index of Radium','is',alkaline_earth_metals[10])
print('Negative index of Radium','is',alkaline_earth_metals[-2])
print('Total item in alkaline_earth_metals is:',len(alkaline_earth_metals))
high=max(alkaline_earth_metals,key=lambda x:(isinstance(x,int),x))
print('The highest atomic number in list is:',high)

Bai 4
List: [1830, 2314, 2956, 3900, 4353, 4492, 5566, 9362]
Index of 9362 in default list is: 3
---------------------------
Bai 5
Index of radium is:  10
Positive index of Radium is radium
Negative index of Radium is radium
Total item in alkaline_earth_metals is: 12
The highest atomic number in list is: 88

In [3]:
print('Bai 6')
temps1=[]
temps=[25.2,16.8, 31.4, 23.9, 28, 22.5,19.6]
temps1.extend(temps)
temps1.sort()
cool_temps=temps1[:2]
warm_temps=temps1[2:]
temps_in_celsius=cool_temps+warm_temps
print('DEFAULT TEMPS LIST:',temps,'\n')
print('COOL TEMPS LIST(ABOVE 20 DEGREES):',cool_temps,'\n')
print('WARM TEMPS LIST(BELOW 20 DEGREES):',warm_temps,'\n')
print('TEMPS IN CELSIUS:',temps_in_celsius) 
print('---------------------------')
print('Bai 7')
def same_first_last(L:list): #len>=2
       if L[0]==L[-1]:
              return True
       else:
              return False
print(same_first_last([3,2,1,3]))
print(same_first_last(['apple', 'banana', 'pear']))
print(same_first_last([4.0, 4.5]))

Bai 6
DEFAULT TEMPS LIST: [25.2, 16.8, 31.4, 23.9, 28, 22.5, 19.6]

COOL TEMPS LIST(ABOVE 20 DEGREES): [16.8, 19.6]

WARM TEMPS LIST(BELOW 20 DEGREES): [22.5, 23.9, 25.2, 28, 31.4]

TEMPS IN CELSIUS: [16.8, 19.6, 22.5, 23.9, 25.2, 28, 31.4]
---------------------------
Bai 7
True
False
False

In [4]:
print('Bai 8')
def is_longer(L1:list,L2:list):
       if len(L1)>len(L2):
              return True
       else:
              return False
print(is_longer([1, 2, 3], [4, 5])
)
print(is_longer(['abcdef'], ['ab', 'cd', 'ef']))
print(is_longer(['abcdef'], ['ab', 'cd', 'ef']))
print('---------------------------')
print('Bai 9:\n Example 1:\n')
values=[0,1,2]
values[1]=values
if (id(values)==id(values[1])):
       print('Same')

values=[0,1,2,3]
if (id(values)!=id(values[1])):
       print('Different')
print('\n Example 2:')
values=[0,1,2]
values[1]=values
print('values[1]:',values[1])
values=[0,1,2,3]
print('values[1]:',values[1])
print('---------------------------')
print('Bai 10')
nested_list=[['km', 'miles', 'league'],['kg', 'pound', 'stone']]
first_inner=nested_list[0]
last_inner=nested_list[1]
km=first_inner[0]
kg=last_inner[0]
mileleague=first_inner[1:3]
kgpound=last_inner[0:2]
print(first_inner)
print(last_inner)
print(km)
print(kg)
print(mileleague)
print(kgpound)
print('---------------------------')
print('Bai 11: Negative indices as task 10 \n')
first_inner2=nested_list[-2]
last_inner2=nested_list[-1]
km2=first_inner[-3]
kg2=last_inner[-3]
mileleague2=first_inner2[-2:]
kgpound2=last_inner2[:-1]
print(first_inner2)
print(last_inner2)
print(km2)
print(kg2)
print(mileleague2)
print(kgpound2)

Bai 8
True
False
False
---------------------------
Bai 9:
 Example 1:

Same
Different

 Example 2:
values[1]: [0, [...], 2]
values[1]: 1
---------------------------
Bai 10
['km', 'miles', 'league']
['kg', 'pound', 'stone']
km
kg
['miles', 'league']
['kg', 'pound']
---------------------------
Bai 11: Negative indices as task 10

['km', 'miles', 'league']
['kg', 'pound', 'stone']
km
kg
['miles', 'league']
['kg', 'pound']

In [5]:
#CHUONG 9
print('---------------------------')
print('Bai 1')
celegans_phenotypes=['Emb','Him', 'Unc', 'Lon', 'Dpy', 'Sma']
for phenotype in celegans_phenotypes:
       print(phenotype)
print('---------------------------')
print('Bai 2')
half_lives=[87.74, 24110.0,6537.0, 14.4, 376000.0 ]
for value in half_lives:
       print(value,end=' ;')
print()
print('---------------------------')
print('Bai 3')
whales=[5, 4, 7, 3, 2, 3, 2, 6, 4, 2, 1, 7, 1, 3]
more_whale=[]
for count in whales:
       more_whale.append(count +1)
print(more_whale)
print('---------------------------')
print('Bai 4')
number_and_weight=[]
earthmetal=[['beryllium',4,9.012],['magnesium',12,24.305],
            ['calcium',20,40.078],['strontium',38,87.62],
            ['barium',56,137.327],['radium',88,226],]
for i in earthmetal:
       print(i[1:])
print('---------------------------')
print('Bai 5')
def mystery_function(values):#Khoi tao ham va chen vao tham so values
       result=[] #Khai bao 1 list result rong
       for sublist in values: #Cho vong lap sublist chay trong bien values
              result.append([sublist[0]])#Them sublist co index=0 vao list result
              for i in sublist[1:]:#Cho vong lap i chay trong vong lap sublist tu index 1 tro di
                     result[-1].insert(0,i)
                     return result
print('---------------------------')
print('Bai 6')
while True:
       a=input("If you want to stop ! - Type 'Quit' or 'QUIT':")
       if a=='Quit'or a=='QUIT':
              print("Succesfully stop")
              break
       else:
              print("Please type again")
              continue 
print('---------------------------')
print('Bai 7')
#########################################
#########################################
print('---------------------------')
print('Bai 8')
print('---------------------------')
print('Bai 9')
for i in range(33,50):
       print(i,end=' ')

---------------------------
Bai 1
Emb
Him
Unc
Lon
Dpy
Sma
---------------------------
Bai 2
87.74 ;24110.0 ;6537.0 ;14.4 ;376000.0 ;
---------------------------
Bai 3
[6, 5, 8, 4, 3, 4, 3, 7, 5, 3, 2, 8, 2, 4]
---------------------------
Bai 4
[4, 9.012]
[12, 24.305]
[20, 40.078]
[38, 87.62]
[56, 137.327]
[88, 226]
---------------------------
Bai 5
---------------------------
Bai 6
If you want to stop ! - Type 'Quit' or 'QUIT':Quit
Succesfully stop
---------------------------
Bai 7
---------------------------
Bai 8
---------------------------
Bai 9
33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49

In [6]:
print('---------------------------')
print('Bai 10')
for i in range(10,0,-1):
       print(i,end=' ')
print('---------------------------')
print('Bai 11')
tong=0
for i in range(2,23):
       dodai=22-2
       tong+=i
       trungbinh=tong/dodai
print('Tong=',tong,'Trung binh=',trungbinh)
print('---------------------------')
print('Bai 12')
from typing import List
def remove_neg(num_list: List[float]):
       for i in set(num_list):
              if i<0:
                     num_list.remove(i)
       print(num_list)
numbers=[-5,1,-3, 2,-3,6,-4,-5,8,11]
remove_neg(set(numbers))
print('---------------------------')
print('Bai 13')
for i in range(7):
       for j in range(i+1):
              print('T',end=' ')
       print('')
print('---------------------------')
print('Bai 14')
k = 14 - 2
for i in range(0, 7):
        for j in range(0, k):
            print(end=" ")
        k = k - 2
        for j in range(0, i+1):
            print("T ", end="")
        print("\r")
print('---------------------------')
print('Bai 15')
n = 7
i = 1
while i <= n :
    j = 1
    while j <= i:
        print("T", end = " ")
        j += 1
    print()
    i += 1
#TRIANGEL 2
print('---------------------------')
print('Bai 16')

---------------------------
Bai 10
10 9 8 7 6 5 4 3 2 1 ---------------------------
Bai 11
Tong= 252 Trung binh= 12.6
---------------------------
Bai 12
{1, 2, 6, 8, 11}
---------------------------
Bai 13
T
T T
T T T
T T T T
T T T T T
T T T T T T
T T T T T T T
---------------------------
Bai 14
            T
          T T
        T T T
      T T T T
    T T T T T
  T T T T T T
T T T T T T T
---------------------------
Bai 15
T
T T
T T T
T T T T
T T T T T
T T T T T T
T T T T T T T
---------------------------
Bai 16